# Dockerfile for building the image for omnibus-server.
FROM ghcr.io/astral-sh/uv:python3.11-alpine

# Authors
LABEL authors="Kenny Jiang <k72jiang@uwaterloo.ca>"

# Expose: XXXXX

# Install git.
RUN apk add --no-cache git

# Copy the project into the image.
WORKDIR /app
ADD . /app

# Sync the project into the new environment, asserting the lockfile is up to date.
RUN uv sync --project src/sources/parsley --locked

# Run the server.
ENTRYPOINT ["uv", "run", "src/sources/parsley/main.py"]