MESSAGE_FORMAT = [
    ("VA1 Command", "?"),
    ("VA2 Command", "?"),
    ("VA3 Command", "?"),
    ("VA4 Command", "?"),
    ("Ignition Primary Command", "?"),
    ("Ignition Secondary Command", "?"),
    ("Rocket Power Command", "?"),
    ("Fill Disconnect Command", "?"),
    ("Towerside Main Batt", "H"),
    ("Towerside Actuator Batt", "H"),
    ("Error Code", "H"),
    ("Towerside Armed", "?"),
    ("Towerside Has Contact", "?"),
    ("Ignition Primary Current", "H"),
    ("Ignition Secondary Current", "H"),
    ("VA1 Lims", "B"),
    ("VA2 Lims", "B"),
    ("VA3 Lims", "B"),
    ("VA4 Lims", "B"),
    ("Fill Disconnect Lims", "B"),
]
