name: Increment Major Version

on:
  pull_request:
    paths:
      - 'omnibus/**'
    branches:
      - master
      - shirleyfyx/134-major-version-increment

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Increment Version
        run: python .github/workflows/increment_version.py
          
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add omnibus/release_info.py
          git commit -m "Increment major version to $NEW_VERSION"
          git push origin HEAD:${{ github.head_ref }}
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}
      
      